

logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: wxlsp1
#    password: wxlsp1
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://tx.zhongruigo.com/wxl_sp1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: zhyspboot
    password: zhyspboot
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://tx.zhongruigo.com/zhy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

server:
  port: 8088